### ISSUE TITLE
Making it so that when a data point is added to the child, we only get that new value instead of the entire node

### ISSUE THREAD

**Issue by TellesF22** [Snow-Sense/FirebaseDataRealTimeGraph#3]
Hi Dr. Nitya, I remember you mentioning this in our meeting on Wednesday.  Could you please remind me of what the name of the code snippet for that?

Thanks.

**Comment by nitya** [comment]
Hey Felipe -- look at https://firebase.google.com/docs/database/admin/retrieve-data

Think of database as a tree.
The reference = a node in tree that you get an address for, which effectively represents that node and all its components by default.

When getting a data point, you will register callbacks that notify you of changes to that node.
 - if you use the "value" event, it will notify you every time ANY data changes in any data (at that node or at any of its children) - this can get expensive
 - if you instead register for child-specific updates, you get notified only when that specific child event happens. In your case, you want to register for the "child_added" event -- now when your app initially loads, you will get one callback for each child that already exists for the node. But after that every time a new child is added, this will get called and will only have the child node's data.

The docs link also has examples. Hope that helps?
